from pydub import AudioSegment
import os


def merge(files, output="final.mp3", provider=None, model=None, voice=None):
    """
    Mescla múltiplos arquivos WAV em um único arquivo MP3.

    Args:
        files: Lista de caminhos para arquivos WAV
        output: Caminho do arquivo MP3 de saída
        provider: 'kokoro' ou 'xtts' (para metadata)
        model: Nome do modelo (ex: 'Kokoro-82M', 'XTTS v2')
        voice: Voz usada (ex: 'pf_dora', 'clonagem')

    Raises:
        ValueError: Se a lista de arquivos estiver vazia
    """
    if not files:
        raise ValueError("Lista de arquivos vazia. Nenhum áudio foi gerado.")

    # Validar existência de arquivos
    missing_files = [f for f in files if not os.path.exists(f)]
    if missing_files:
        raise FileNotFoundError(f"Arquivos não encontrados: {missing_files}")

    combined = AudioSegment.empty()

    for f in files:
        audio = AudioSegment.from_wav(f)
        combined += audio + AudioSegment.silent(duration=400)

    # Exportar com qualidade melhor (160 kbps)
    combined.export(output, format="mp3", bitrate="160k")

    # Adicionar metadata ID3 se possível
    _add_id3_tags(output, provider, model, voice)


def _add_id3_tags(mp3_path, provider=None, model=None, voice=None):
    """Adiciona tags ID3 ao arquivo MP3 para identificar provider/modelo/voz."""
    try:
        from mutagen.id3 import ID3, TIT2, TPE1, TALB, COMM
    except ImportError:
        # mutagen não instalado, pular
        return

    try:
        # Remover tags existentes
        try:
            audio = ID3(mp3_path)
            audio.delete()
        except OSError:
            pass

        # Criar novas tags
        audio = ID3()

        if provider:
            provider_upper = provider.upper()
            audio.add(TIT2(text=[f"Audiobook - {provider_upper}"]))
            audio.add(TPE1(text=[f"{provider_upper} TTS"]))

        if model:
            audio.add(TALB(text=[f"Generated by {model}"]))

        if voice:
            comment = f"Voice: {voice}"
            audio.add(COMM(desc="", lang="eng", text=[comment]))

        # Salvar tags
        audio.save(mp3_path, v2_version=4)
    except Exception:
        # Se falhar, não impedir o processamento
        pass
